### ISSUE TITLE
Browser does not resize

### ISSUE THREAD

**Issue by zspri** [GridTech123/Grid-Web-Browser#1]
![capture](https://cloud.githubusercontent.com/assets/19719195/22866132/ed8c92e4-f13e-11e6-9f64-aafbf5ec5471.PNG)
You can fix this by changing the anchors of the buttons, browser, etc. in the Visual Basic files.

**Comment by GridTech123** [comment]
Thanks I'll get to that in the next week as this is an outdated project that I am not actively developing anymore.
